### PR TITLE
Version 1.1, QR scanning, native encryption

### PR DESCRIPTION
**Pull request by manton**
Adds QR scanning button and Kotlin-based encryption.

@vincentritter Any concerns that we need to address before this release? Looking good for me. I want to update the editor but that can wait until version 1.2.

### CODE REVIEW

**Comment by vincentritter** [comment]
Great stuff @manton! I want to give Android a quick test tomorrow and see if everything is working as it should — then I'm happy to merge this.

RE: Privacy manifest — yes, same thing here locally and I don't understand what has happened. I know the RN team started adding these automatically (they also seem to have back-ported them to older versions).

**Comment by manton** [comment]
I'm submitting the iOS version while we finish testing Android.

**Comment by manton** [comment]
iOS was approved already. I think I'll release it today, Android to follow later in the week.

**Comment by vincentritter** [comment]
Sounds good @manton. I am working through some Android specific changes at the moment.

**Comment by manton** [comment]
@vincentritter Cool. Any other testing we should do? I'll do an upload of the latest build but we can wait to submit to Google until you're good with it.

**Pull request merged**
